---
engines:
  csslint:
    enabled: false
  coffeelint:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
      - ruby
  eslint:
    enabled: false
  fixme:
    enabled: false
  rubocop:
    enabled: false
ratings:
  paths:
  - "**.rb"
exclude_paths:
- '/public/'
